# Generated by Django 2.0.5 on 2018-05-22 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='description',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
