# Generated by Django 2.0.5 on 2018-05-22 05:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0002_toy_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
