# Generated by Django 2.0.5 on 2018-05-22 05:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0003_toy_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='release_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toy',
            name='toy_category',
            field=models.CharField(default='', max_length=200),
        ),
    ]
