# Generated by Django 2.0.5 on 2018-05-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0004_auto_20180522_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='was_included_in_home',
            field=models.BooleanField(default=False),
        ),
    ]
