# Generated by Django 2.0.5 on 2018-05-22 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0005_toy_was_included_in_home'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toy',
            options={'ordering': ('name',)},
        ),
    ]
